#ifndef FAULTS_H_
#define FAULTS_H_

#define FAULT_BIT_SPI_GATE_PULSE_WIDTH  0X0001
#define FAULT_BIT_SPI_GATE_DUTY_CYCLE   0X0002
#define FAULT_BIT_SPI_RF_PULSE_WIDTH 	0X0004
#define FAULT_BIT_SPI_RF_DUTY_CYCLE 	0X0008
#define FAULT_BIT_SPI_POWER_SUPPLY 		0X0010
#define FAULT_BIT_SPI_THERMAL 		    0X0020
#define FAULT_BIT_SPI_VSWR              0X0040
#define FAULT_BIT_SPI_MAX_POWER         0X0080
#define FAULT_BIT_SPI_UNDER_VOLT        0X0100
#define FAULT_BIT_SPI_OVER_VOLT         0X0200
#define FAULT_BIT_SPI_OVER_CURRENT      0X0400
#define FAULT_BIT_SPI_OVERDRIVE         0X0800
#define FAULT_BIT_SPI_INTCON            0X1000


#endif /* FAULTS_H_ */
